openapi: 3.2.0
info:
  title: InstiApp Pass Login API
  description: InstiApp IIT Bombay API
  termsOfService: https://insti.app/tos.html
  contact:
    email: devcom@iitb.ac.in
  license:
    name: AGPLv3
  version: v1
servers:
- url: https://gymkhana.iitb.ac.in/instiapp/api
security:
- Basic: []
tags:
- name: pass_login
paths:
  /pass-login:
    parameters: []
    get:
      operationId: pass_login
      description: ''
      responses:
        '200':
          description: ''
      tags:
      - pass_login
      summary: Pass login
      x-summary-source: derived
components:
  securitySchemes:
    Basic:
      type: http
      scheme: basic
