openapi: 3.2.0
info:
  title: InstiApp Logout API
  description: InstiApp IIT Bombay API
  termsOfService: https://insti.app/tos.html
  contact:
    email: devcom@iitb.ac.in
  license:
    name: AGPLv3
  version: v1
servers:
- url: https://gymkhana.iitb.ac.in/instiapp/api
security:
- Basic: []
tags:
- name: Logout
paths:
  /logout:
    parameters: []
    get:
      operationId: logout
      description: Log out.
      responses:
        '200':
          description: ''
      tags:
      - Logout
      summary: Logout
      x-summary-source: derived
components:
  securitySchemes:
    Basic:
      type: http
      scheme: basic
