openapi: 3.2.0
info:
  title: InstiApp Delete API
  description: InstiApp IIT Bombay API
  termsOfService: https://insti.app/tos.html
  contact:
    email: devcom@iitb.ac.in
  license:
    name: AGPLv3
  version: v1
servers:
- url: https://gymkhana.iitb.ac.in/instiapp/api
security:
- Basic: []
tags:
- name: Delete
paths:
  /interests/{id}:
    parameters:
    - name: id
      in: path
      description: A UUID string identifying this user interest.
      required: true
      schema:
        type: string
        format: uuid
    delete:
      operationId: delete
      description: Delete a user interest.
      responses:
        '204':
          description: ''
      tags:
      - Delete
      summary: Delete
      x-summary-source: derived
components:
  securitySchemes:
    Basic:
      type: http
      scheme: basic
