openapi: 3.2.0
info:
  title: InstiApp Resend Alumni Otp API
  description: InstiApp IIT Bombay API
  termsOfService: https://insti.app/tos.html
  contact:
    email: devcom@iitb.ac.in
  license:
    name: AGPLv3
  version: v1
servers:
- url: https://gymkhana.iitb.ac.in/instiapp/api
security:
- Basic: []
tags:
- name: resend_alumni_otp
paths:
  /resendAlumniOTP:
    parameters: []
    get:
      operationId: resend_alumni_otp
      description: Login
      responses:
        '200':
          description: ''
      tags:
      - resend_alumni_otp
      summary: Resend alumni otp
      x-summary-source: derived
components:
  securitySchemes:
    Basic:
      type: http
      scheme: basic
