openapi: 3.2.0
info:
  title: InstiApp Alumni Otp Conf API
  description: InstiApp IIT Bombay API
  termsOfService: https://insti.app/tos.html
  contact:
    email: devcom@iitb.ac.in
  license:
    name: AGPLv3
  version: v1
servers:
- url: https://gymkhana.iitb.ac.in/instiapp/api
security:
- Basic: []
tags:
- name: alumni_otp_conf
paths:
  /alumniOTP:
    parameters: []
    get:
      operationId: alumni_otp_conf
      description: Login
      responses:
        '200':
          description: ''
      tags:
      - alumni_otp_conf
      summary: Alumni otp conf
      x-summary-source: derived
components:
  securitySchemes:
    Basic:
      type: http
      scheme: basic
