openapi: 3.2.0
info:
  title: InstiApp Shortestpath API
  description: InstiApp IIT Bombay API
  termsOfService: https://insti.app/tos.html
  contact:
    email: devcom@iitb.ac.in
  license:
    name: AGPLv3
  version: v1
servers:
- url: https://gymkhana.iitb.ac.in/instiapp/api
security:
- Basic: []
tags:
- name: shortestpath
paths:
  /shortestpath/:
    parameters: []
    post:
      operationId: shortestpath_create
      description: ''
      responses:
        '201':
          description: ''
      tags:
      - shortestpath
      summary: Shortestpath create
      x-summary-source: derived
components:
  securitySchemes:
    Basic:
      type: http
      scheme: basic
