openapi: 3.2.0
info:
  title: InstiApp Get All User Tags API
  description: InstiApp IIT Bombay API
  termsOfService: https://insti.app/tos.html
  contact:
    email: devcom@iitb.ac.in
  license:
    name: AGPLv3
  version: v1
servers:
- url: https://gymkhana.iitb.ac.in/instiapp/api
security:
- Basic: []
tags:
- name: get_all_user_tags
paths:
  /user-tags:
    parameters: []
    get:
      operationId: get_all_user_tags
      description: Get a list of categories of user tags with nested tags.
      responses:
        '200':
          description: ''
      tags:
      - get_all_user_tags
      summary: Get all user tags
      x-summary-source: derived
components:
  securitySchemes:
    Basic:
      type: http
      scheme: basic
