openapi: 3.2.0
info:
  title: InstiApp External Blog API
  description: InstiApp IIT Bombay API
  termsOfService: https://insti.app/tos.html
  contact:
    email: devcom@iitb.ac.in
  license:
    name: AGPLv3
  version: v1
servers:
- url: https://gymkhana.iitb.ac.in/instiapp/api
security:
- Basic: []
tags:
- name: external_blog
paths:
  /external-blog:
    parameters: []
    get:
      operationId: external_blog
      description: Get External Blog.
      responses:
        '200':
          description: ''
      tags:
      - external_blog
      summary: External blog
      x-summary-source: derived
components:
  securitySchemes:
    Basic:
      type: http
      scheme: basic
