openapi: 3.2.0
info:
  title: InstiApp Check API
  description: InstiApp IIT Bombay API
  termsOfService: https://insti.app/tos.html
  contact:
    email: devcom@iitb.ac.in
  license:
    name: AGPLv3
  version: v1
servers:
- url: https://gymkhana.iitb.ac.in/instiapp/api
security:
- Basic: []
tags:
- name: Check
paths:
  /check/:
    parameters: []
    get:
      operationId: check_list
      description: ''
      responses:
        '200':
          description: ''
      tags:
      - Check
      summary: Check list
      x-summary-source: derived
components:
  securitySchemes:
    Basic:
      type: http
      scheme: basic
